<div style="font-family: Arial; text-align: center;">

## Reinforcement Learning

#### Kannan Singaravelu, CQF

# Reinforcement Learning


Reinforcement learning (RL) is one of three machine learning paradigms, alongside supervised learning and unsupervised learning. RL differs from supervised learning as it focus on finding a balance between exploration and exploitation.


In this approach, the (algorithm) agents take actions in an environment in order to maximize its cumulative reward. The environment is typically stated in the form of a Markov decision process (MDP), because many reinforcement learning algorithms for this context utilize dynamic programming techniques.

MDP is a discrete-time stochastic control process and provides a mathematical framework for modeling decision making in situations where outcomes are partly random and partly under the control of a decision maker. Such processes are useful in optimization problems solved via dynamic programming and reinforcement learning.


RL framework is extremely promising in trading and investment management. Currently RL is mostly a research area and hasn’t yet had significant practical successes beyond games. However, it’s an idea whose time has come.


## Fundamental Notions


Following are some of the fundamental notions of the RL


<img src="20240603_Py_ReinforcementLearning1.jpg"/>

***Environment*** : The world through which agents moves. The environment defines the problem at hand. For example, the environment can be a financial market to be traded in.

***State*** : Current condition returned by the environment. A state subsumes all relevant parameters that describe the current state of the environment. In a financial market, this might include current and historical price levels or financial indicators such as moving averages, macroeconomic variables, and so on.


***Agent*** : The RL algorithm that learns from the exploration and exploitation. Agent subsumes all elements of the RL algorithm that interacts with the environment and learns from these interactions. In a financial context, the agent could represent a trader placing bets on rising or falling markets.


***Action*** : All possible steps that the agent can take from a (limited) set of allowed actions. In a financial market, going long or short could be admissible actions.


***Reward*** : An instant return from the environment to appraise the last action. In a financial context, profit (or loss) is a standard reward.

***Policy*** : The approach the agent uses to determine the next action based on the current state. In a financial context, a trading bot that observes three price increases in a row might decide to buy the market.


***Value*** : The expected long-term return with discount, as opposed to short-term rewards. For a financial trading bot, this might be the expected accumulated trading profit.

***Episode*** : The set of steps from the initial state of the environment until success is achieved or failure is observed. In the financial world, this might be from the beginning of the year to the end of the year or to bankruptcy.


## RL Algorithms

![Description or alt text](20240603_Py_ReinforcementLearning2.svg)

A non-exhaustive, but useful taxonomy of algorithms in modern RL [1]


## Markov Decision Process


MDP is the mathematical formulation of the RL problem where it uses the Markov property where the current state completely characterises the state of the world and is defined by $(S,A,R,P,\gamma)$, where

- $S$: set of possible states
- $A$: set of possible actions
- $R$: distribution of reward given (state, action) pair
- $P$: transition probability, i.e., distribution over next state given (state, action) pair
- $\gamma$: discount factor

The MDP process is as follows,

- Environment samples initial state at $S_0 p(s_0)$ at $t = 0$

- Then, for $t = 0$ until done:
  - agent selects action $a_t$
  - environment samples reward $r_t R(\cdot \mid s_t, a_t)$
  - environment samples next state $s_{t+1} P(\cdot \mid s_t, a_t)$
  - agent receives reward $r_t$ and next state $s_{t+1}$

- Policy $\pi$ is a function from $S$ to $A$ that specifies what action to take in each state

- Objective: find policy $\pi^*$ or value $Q^*$ that maximizes cumulative discounted reward: $\sum_{t>0} \gamma^t r_t$

## Shortest Path Problem

<img src="20240603_Py_ReinforcementLearning3.jpg"/>

The markov decision process is used to find the shortest path between A and D with maximum reward. In this example,
* Set of states are denoted by nodes {A,B,C,D}
* Action is to traverse from one node to another
* Reward is the cost represented by each edge
* Policy is the path taken to reach the destination {A >> C >> D}

## Q-Learning


**Q-learning** is a model-free reinforcement learning algorithm to learn quality of actions telling an agent what action to take under what circumstances. Q-learning finds an optimal policy by maximizing the expected value of the total reward over any and all successive steps, starting from the current state.


Q-learning is an algorithm that takes into account delayed rewards in addition to immediate rewards from an action. There is an action-value policy Q, which assigns a value to every combination of a state and an action. Higher the value, the better the action from the point of view of the agent. Agent who uses the policy Q to choose an action, selects the action with the highest value.


<img src="20240603_Py_ReinforcementLearning4.png"/>

**How is the value of an action derived?**

The value of an action is composed of its direct reward and the discounted value of the optimal action in the next state. The following is the formal expression:

The value of an action is composed of its direct reward and the discounted value of the optimal action in the next state. The following is the formal expression:
$$Q(S_t, A_t) = R_t + \gamma \max_{a} Q(S_{t+1}, a)$$
where, $S_t$ is the state at timestep $t$, $A_t$ is the action taken at state $S_t$, $R_t$ is the direct reward of action $A_t$, $\gamma\in\left[0,1\right]$ is the discount factor, and $\max_{a} Q(S_{t+1}, a)$ is the maximum delayed reward given the optimal action from the current policy $Q$.

To find the optimal policy, we use value iteration algorithm that use the above Bellman equation as an iterative update where $Q_i$ will converge to optimal $Q^*$ as $i \to \infty$.

Such approach is not scalable as it is computationally infeasible to compute for entire state space. To address this we use a function approximator to estimate the action-value function $Q(s, a; \theta) \approx Q^*(s, a)$. If the function approximator is a deep neural network, then we call this as **deep q-leaning**.

## Q-Learning Example


In a simple environment with a limited number of possible states, Q can be represented by a table, where we can list all state-action combination with the corresponding value.

Let's initialize $Q$ as a zero matrix and $R$ as below:

$$
\begin{array}{cc}
Q = \begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 \\
\end{bmatrix}
&
R = \begin{bmatrix}
-1 & -1 & -1 & -1 & 0 & -1 \\
-1 & -1 & 0 & -1 & -1 & 100 \\
-1 & -1 & 0 & -1 & -1 & -1 \\
0 & -1 & -1 & -1 & 100 & -1 \\
-1 & 0 & -1 & -1 & 0 & -1 \\
-1 & -1 & -1 & 100 & -1 & 0 \\
\end{bmatrix}
\end{array}
$$

$\gamma$ ranges from 0 to 1. $\gamma \sim 0$, the agent will consider immediate rewards; $\gamma \sim 1$, the agent will consider future rewards with higher weights. For this example, let us consider an initial state of 1 with $\gamma = 0.80$ to calculate the Q-value.
$$Q(\text{state, action}) = R(\text{state, action}) + \gamma \times \max[\{Q(\text{next state, all actions})\}]$$

$Q(1,5) = R(1,5) + 0.80 \times \max[Q(5,1), Q(5,4), Q(5,5)] = 100 + 0.80 = 100$

In [3]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [4]:
# R matrix
R = np.array([[-1,-1,-1,-1,0,-1],
             [-1,-1,-1,0,-1,100],
             [-1,-1,-1,0,-1,-1],
             [-1,0,0,-1,0,-1],
             [-1,0,0,-1,-1,100],
             [-1,0,-1,-1,0,100]])

print(f'Reward Matrix \n \n {R}')

Reward Matrix 
 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1   0  -1]
 [ -1   0   0  -1  -1 100]
 [ -1   0  -1  -1   0 100]]


In [5]:
# Q Matrix
Q = np.array(np.zeros([6,6]))
print(f'Q Matrix \n \n {Q}')

Q Matrix 
 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Let's now return all available actions in the state given as an argument


In [6]:
# Initial State - choosen at random
initial_state = 1

# Gamma (discount paramaters)
gamma = 0.8

In [7]:
np.where(R[1]>=0)[0]

array([3, 5], dtype=int64)

In [8]:
# Let's now return all available actions in the state given as an argument
def available_actions(state):
    current_state_row = R[state]
    aaction = np.where(current_state_row >=0)[0]
    return aaction

# Get available actions in the current state
available_act = available_actions(initial_state)
available_act

array([3, 5], dtype=int64)

Let's choose which action to be performed (at random) within the range of all available actions


In [9]:
# Next action to be performed
def next_action(available_action_range):
    naction = int(np.random.choice(available_act,1))
    return naction

# Action to be performed
action = next_action(available_act)
action

5

Let's now update the Q Matrix according to the path selected and the Q learning algorithm


In [10]:
# Update Q Matrix
def update(current_state, action, gamma):
    max_index = np.where(Q[action,] == np.max(Q[action,]))[0]
    
    if max_index.shape[0] > 1:
        max_index = int(np.random.choice(max_index,size=1))
    else:
        max_index = int(max_index)
    
    max_value = Q[action, max_index]
    
    # Q learning formula 
    Q[current_state, action] = R[current_state, action] + gamma * max_value
    
# Update Q-matrix
update(initial_state, action, gamma)

### Training

In [11]:
# Training for 10000 iterations

for i in range(10000):
    current_state = np.random.randint(0,int(Q.shape[0]))
    available_act = available_actions(current_state)
    action = next_action(available_act)
    update(current_state, action, gamma)
    
# Normalize the Q matrix
print(f'Trained Q-Matrix \n \n {Q/np.max(Q)*100}')

Trained Q-Matrix 
 
 [[  0.    0.    0.    0.   80.    0. ]
 [  0.    0.    0.   64.    0.  100. ]
 [  0.    0.    0.   64.    0.    0. ]
 [  0.   80.   51.2   0.   80.    0. ]
 [  0.   80.   51.2   0.    0.  100. ]
 [  0.   80.    0.    0.   80.  100. ]]


### Testing

In [12]:
current_state = 2
steps = [current_state]

while current_state !=5:
    next_step_index = np.where(Q[current_state,] == np.max(Q[current_state,]))[0]
    
    if next_step_index.shape[0] > 1:
        next_step_index = int(np.random.choice(next_step_index,size=1))
    else:
        next_step_index = int(next_step_index)
        
    steps.append(next_step_index)
    current_state = next_step_index

### Selectetd Sequence


In [13]:
# Print selected sequence of steps
print(f'Selected Path {steps}')

Selected Path [2, 3, 1, 5]


## OpenAI Gym

OpenAI [2] is an organization that facilitate research in RL. OpenAI has developed and open sourced a suite of environments, called `OpenAI Gym` that allows the training of RL agents via a standardized API.

The gym library addressed two important gaps that were slowing down the RL research.
1. Need for better benchmarks
2. Lack of standardization of environments used in publications

Gym is a toolkit for developing and comparing RL algorithms and makes no assumptions about the structure of the agent. It is compatible with any numerical computation library, such as TensorFlow or Theano. The gym library is a collection of environments that we can use to work out the RL algorithms. These environments have a shared interface, allowing us to write general algorithms.

### Installation


In [14]:
#!pip install gym

In [15]:
#!pip install gymnasium
#!pip install pygame

### Environments

Here’s an example of cart-pole environment which will run an instance of the CartPole-v0 environment for 1000 timesteps, rendering the environment at each step.

In [16]:
import gymnasium as gym
env = gym.make("CartPole-v1", render_mode="human")

env.reset()
for _ in range(200):
    env.render()
    env.step(env.action_space.sample())  # take a random action

### Observations


Observing the outcome of our action is critical for us to do better than random actions. The environment’s step function returns exactly what we need by returning the following four values.

`observation` (**object**): an environment-specific object representing the observation of the environment. For example, pixel data from a camera, joint angles and joint velocities of a robot, or the board state in a board game.

`reward` (**float**): The amount of reward returned as a result of taking the action. The scale varies between environments, but the goal is always to increase your total reward.

`terminated` (**bool**): – whether a terminal state (as defined under the MDP of the task) is reached. In this case further step() calls could return undefined results.

`truncated` (**bool**) – whether a truncation condition outside the scope of the MDP is satisfied. Typically a timelimit, but could also be used to indicate agent physically going out of bounds. Can be used to end the episode prematurely before a terminal state is reached.

`done` (**boolean**): whether it’s time to `reset` the environment again. Most (but not all) tasks are divided up into well-defined episodes, and `done` being `True` indicates the episode has terminated. (For example, perhaps the pole tipped too far, or you lost your last life.)

`info` (**dict**): diagnostic information useful for debugging. It can sometimes be useful for learning (for example, it might contain the raw probabilities behind the environment’s last state change). However, official evaluations of your agent are not allowed to use this for learning.

This is just an implementation of the classic “agent-environment loop”. Each timestep, the agent chooses an `action` and the environment returns an `observation` and a `reward`.


<img src="20240603_Py_ReinforcementLearning5.png"/>

The process gets started by calling `reset()`, which returns an initial `observation`. So a more proper way of writing the previous code would be to respect the `done` flag. The observation (state) of the environment is given by four parameters, describing the physical measurements: cart position, cart velocity, pole angle, and pole velocity (at tip).

### Spaces

In the above examples, we've been sampling random actions from the environment's action space. But what actually are those actions? Every environment comes with an `action_space` and an `observation_space`. These attributes are of type `Space`, and they describe the format of valid actions and observations.

In [17]:
# action space
env.action_space

Discrete(2)

In [18]:
# state or observation space
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

The `Discrete` space allows a fixed range of non-negative numbers, so in this case valid `action`s are either 0 or 1. The `Box` space represents an $n$-dimensional box, so valid `observations` will be an array of 4 numbers.


In [19]:
# check box bounds
print(f'High: {env.observation_space.high}')
print(f'Low: {env.observation_space.low}')

High: [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
Low: [-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


## Learning Objective


In [20]:
env.reset()
for e in range(1, 200):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)                 # stepping forward one step 
    print(f'step={e:2d} | state={observation} | action={action} | reward={reward}')
    if (terminated or truncated) and (e + 1) <= 200:                                    # failure if less than 200 steps
        print('*** FAILED ***')
        break

step= 1 | state=[-0.01339098  0.19733317 -0.01319055 -0.31613022] | action=1 | reward=1.0
step= 2 | state=[-0.00944431  0.3926405  -0.01951315 -0.61294365] | action=1 | reward=1.0
step= 3 | state=[-0.0015915   0.5880296  -0.03177202 -0.91170806] | action=1 | reward=1.0
step= 4 | state=[ 0.01016909  0.7835667  -0.05000619 -1.214205  ] | action=1 | reward=1.0
step= 5 | state=[ 0.02584042  0.5891244  -0.07429029 -0.93760186] | action=0 | reward=1.0
step= 6 | state=[ 0.03762291  0.7851652  -0.09304233 -1.2526733 ] | action=1 | reward=1.0
step= 7 | state=[ 0.05332622  0.9813477  -0.11809579 -1.5729891 ] | action=1 | reward=1.0
step= 8 | state=[ 0.07295316  0.78781587 -0.14955558 -1.3193529 ] | action=0 | reward=1.0
step= 9 | state=[ 0.08870948  0.9844783  -0.17594263 -1.6548593 ] | action=1 | reward=1.0
step=10 | state=[ 0.10839905  1.1811632  -0.2090398  -1.9967927 ] | action=1 | reward=1.0
step=11 | state=[ 0.13202232  1.3777697  -0.24897566 -2.3462934 ] | action=1 | reward=1.0
*** FAILED

## References


[1] [OpenAI Spinning Up](https://urldefense.com/v3/__https://spinningup.openai.com/en/latest/index.html__;!!KGvANbslH1YjwA!9U83PW6hTtjaGWAdnbEhuGXT52hTBHA_7H7DaLF4x-Tt-t33K3c6LL27gG56cQAp7nYn2Cd3AYy-OWX0L_CBqt6KcZbRYFo7TiQ$)

[2] [OpenAI Gym](https://urldefense.com/v3/__https://www.gymlibrary.dev/__;!!KGvANbslH1YjwA!9U83PW6hTtjaGWAdnbEhuGXT52hTBHA_7H7DaLF4x-Tt-t33K3c6LL27gG56cQAp7nYn2Cd3AYy-OWX0L_CBqt6KcZbRvQRpyGw$)

[Kannan Singaravelu.](https://www.linkedin.com/in/kannansi/) | [GitHub](https://urldefense.com/v3/__https://github.com/kannansingaravelu__;!!KGvANbslH1YjwA!9U83PW6hTtjaGWAdnbEhuGXT52hTBHA_7H7DaLF4x-Tt-t33K3c6LL27gG56cQAp7nYn2Cd3AYy-OWX0L_CBqt6KcZbR2-XAC4M$) | [LinkedIn](https://urldefense.com/v3/__https://www.linkedin.com/in/kannansi__;!!KGvANbslH1YjwA!9U83PW6hTtjaGWAdnbEhuGXT52hTBHA_7H7DaLF4x-Tt-t33K3c6LL27gG56cQAp7nYn2Cd3AYy-OWX0L_CBqt6KcZbRDD453dU$) 